import json

from prompts import get_system_description
from params import get_running_params, get_env_params, get_LLM_configs
from internal_tools import raise_error

running_params = get_running_params()
env, env_params = get_env_params(running_params['system'])
client, MODEL = get_LLM_configs()

# %% Evaluator agent
class Evaluator:
    def __init__(self):
        self.history = []

    def evaluate(self, traj, query):
        """
        Analyze the trajectory generated by error based on the code generated by Coder agent and return suggestions for modification.
        Args:
            traj (dict): Dictionary of the trajectory, consists of 'x', 'u', and 'r'.
            query (str): Original query string raised by the user
        """
        evaluator_prompt = """
        You are an evaluator that determines whether the Policy generator agent has produced a correct contrastive policy.
        You will be given a modified trajectory in JSON format, represented as a list where each object corresponds to 
        one timestep and includes all state and action values.
        Interpret these trajectories as sequential time-series.
        If you thought that the modified trajectory from the policy faithfully follow the intention from the user query, 
        you can confirm the contrastive policy, otherwise raise an error by calling raise error tool.
            
        For accurate evaluation of the trajectory, here are some descriptions of the control system:
        {system_description}
        
        Also, environment parameters used in process control:
        {env_params}
        
        Here are a few points to consider when evaluating the modified trajectory.
        - Do not consider the 'timestep' information in the query, since it has already been reflected in the trajectory.
        """

        messages = [
            {"role": "system", "content": evaluator_prompt.format(
                system_description=get_system_description(running_params['system']),
                env_params=vars(env)
            )},
            {"role": "user", "content": f"""
            Does the trajectory below faithfully follow the user's intention?
            
            Modified trajectory:
            {traj}
            
            User query:
            {query}
            """
             }
        ]

        tools = [
            {
                "type": "function",
                "name": "raise_error",
                "description": "Raise an error when the request violates constraints (e.g., asks for MPC, PID).",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string",
                            "description": "Error message explaining why the request is not supported."
                        }
                    },
                    "required": ["message"]
                }
            },
            {
                "type": "function",
                "name": "confirm_policy",
                "description": "Confirm that the modified trajectory follows the user's intended contrastive rule",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string",
                            "description": "Message for confirming the trajectory."
                        }
                    },
                    "required": ["message"]
                }
            }
        ]

        response = client.chat.completions.create(
            model=MODEL,
            messages=messages,
            functions=tools,
        )
        if response.choices[0].message.function_call is not None and response.choices[0].message.function_call.name == 'raise_error':
            error_message = json.loads(response.choices[0].message.function_call.arguments)['message']
            raise_error(error_message)
            return False

        return True
